import ProfileLayout from '@/Layouts/ProfileLayout';
import { Head } from '@inertiajs/react';


export default function Welcome(){
    return (
      <ProfileLayout title="Portfolio">
        <div className="overflow-hidden">
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/> ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>
        ASDSADASDASDASDASDASDDADSADSADASD<br/>

        </div>


      </ProfileLayout>
    );
}

